# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

# You don't need to test on very old version of the Go compiler. It's the user's
# responsibility to keep their compilers up to date.
go:
  - 1.11.x

# Only clone the most recent commit.
git:
  depth: 1

before_install:
  - curl -L  https://github.com/coreos/etcd/releases/download/v3.3.3/etcd-v3.3.3-linux-amd64.tar.gz -o etcd-v3.3.3-linux-amd64.tar.gz
  - tar xzvf etcd-v3.3.3-linux-amd64.tar.gz
  - sudo cp ./etcd-v3.3.3-linux-amd64/etcd /usr/bin/etcd
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - curl -L https://github.com/coredns/coredns/releases/download/v1.5.0/coredns_1.5.0_linux_amd64.tgz -o coredns_1.5.0_linux_amd64.tgz
  - tar xzvf coredns_1.5.0_linux_amd64.tgz
  - sudo cp coredns /usr/bin/coredns
  - mkdir /home/travis/.kube
  - curl -L https://raw.githubusercontent.com/tweakmy/fotofona/master/fakekubeconfig -o /home/travis/.kube/config

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

script: dep ensure; go test -v ./...
